sudo: required
services:
    - docker
before_install:
    - docker build -t rajesh5sep/react-test -f ./client/Dockerfile.dev  ./client
script:
    - docker run -e CI=true rajesh5sep/react-test npm test -- --coverage
after_success:
    - docker build -t rajesh5sep/multi-client ./client
    - docker build -t rajesh5sep/multi-nginx ./nginx
    - docker build -t rajesh5sep/multi-server ./server
    - docker build -t rajesh5sep/multi-worker ./worker
#Log in to the docker CLI
    - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
# Push Docker images
    - docker push rajesh5sep/multi-client
    - docker push rajesh5sep/multi-nginx
    - docker push rajesh5sep/multi-server
    - docker push rajesh5sep/multi-worker
